title = "ironfoil"
description = "A tool to transfer to many Nintendo Switch title installers"
base_url = "https://ironfoil.samake.se"
compile_sass = false

[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"
